### ISSUE TITLE
Update npm package?

### ISSUE THREAD

**Issue by tmcw** [kkaefer/node-bitstream#1]
Hey, nice library there :). Currently I'm getting no luck getting the extended bitstream obj from the npm package, but git-cloning in node_modules works great.

**Comment by kkaefer** [comment]
what do you mean with "extended bitstream obj"? bitstream installs just fine for me. Maybe a glitch in npm?

**Comment by MatthewBarker** [comment]
Hi @kkaefer,
What @tmcw meant is that if you install this via npm you get an old version of the code. Although there aren't any tagged versions, it's the commit with the comments "rename _flush to flush()". This commit is missing such functions as writeUnsignedBE , writeUnsignedLE etc. 
This still appears to be the case.
